### ISSUE TITLE
Exception on Movie Delete

### ISSUE THREAD

**Issue by abnersnell** [everettsouthwick/Eraserr#47]
Please close - User Error, extra slash in radarr base URL.

I am using the latest main branch(non docker) and I receive the following after the Plex work is done to identify movies for deletion.  I do have two movie libraries, one managed by Radarr and one managed manually.  I can see from the logs, the Plex work does check both libraries but for the second movie library it will never find anything in Radarr for it.

Traceback (most recent call last):
  File "/home/seed/.local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Eraserr/eraserr.py", line 30, in <module>
    main(args)
  File "/opt/Eraserr/src/main.py", line 24, in main
    job_runner.run()
  File "/opt/Eraserr/src/jobs.py", line 56, in run
    self.get_and_delete_job()
  File "/opt/Eraserr/src/jobs.py", line 79, in get_and_delete_job
    self.get_and_delete_movies()
  File "/opt/Eraserr/src/jobs.py", line 133, in get_and_delete_movies
    media_deleted = self.radarr.get_and_delete_media(media_to_delete, self.dry_run)
  File "/home/seed/.local/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/seed/.local/lib/python3.10/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/home/seed/.local/lib/python3.10/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/opt/Eraserr/src/clients/radarr.py", line 62, in get_and_delete_media
    media = self.__get_media()
  File "/opt/Eraserr/src/clients/radarr.py", line 23, in __get_media
    return response.json()
  File "/home/seed/.local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by everettsouthwick** [comment]
What would you like the behavior to be? To be able to specify multiple Radarr instances or to handle this exception silently?

**Comment by abnersnell** [comment]
I had a a bad config resulting in this error.  It might be beneficial to include the specific libraries you want the program to process under the Plex config section.
