### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'datetime.datetime'

### ISSUE THREAD

**Issue by Jmanhale1** [everettsouthwick/Eraserr#66]
**Describe the bug**
Running the script through docker in a dryrun and got this error.
Traceback (most recent call last):
  File "/app/eraserr.py", line 30, in <module>
    main(args)
  File "/app/src/main.py", line 24, in main
    job_runner.run()
  File "/app/src/jobs.py", line 56, in run
    self.get_and_delete_job()
  File "/app/src/jobs.py", line 83, in get_and_delete_job
    self.get_and_delete_series()
  File "/app/src/jobs.py", line 141, in get_and_delete_series
    media = self.plex.get_expired_media("show", self.sonarr_watched_deletion_threshold, self.sonarr_unwatched_deletion_threshold, self.schedule_interval)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
           ^^^
  File "/app/src/clients/plex.py", line 114, in get_expired_media
    if self.__media_is_expired(item, watched_media_expiry_seconds, unwatched_media_expiry_seconds, schedule_interval):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/clients/plex.py", line 73, in __media_is_expired
    added_at = max(episode.addedAt for episode in media.episodes()) if media.episodes() else added_at
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'datetime.datetime'

**To Reproduce**
1. Run Script after setting up config with all details needed. 
2. Wait for program to run into error.
3. get error

**Expected behavior**
First time i've run the script. Not really sure what happens once it finishes scan. I was hoping for some kind of output file to be created that shows what is going to be deleted.

**Screenshots**
![image](https://github.com/everettsouthwick/Eraserr/assets/3496161/e7a9f5b9-0ebd-4475-8abe-8f0df45c844b)

**Desktop (please complete the following information):**

**Additional context**

**Comment by Jmanhale1** [comment]
I assumed that this was possibly a issue with my library so i removed the libraries and re-added them and it seems to have fixed the issue for me. However might be worth adding a catch for that error.
